### ISSUE TITLE
Reporting intra-RIB conflicts

### ISSUE THREAD

**Issue by nrchandan** [ANSSI-FR/tabi#4]
I have a RIB file with exactly two records, that are in conflict with each other. See pull request link below. In this case, I found out that the detect_conflicts function returns two conflicts. Is this an expected behavior?

https://github.com/ANSSI-FR/tabi/pull/3/files#diff-2f062b81eb0021f04e0686060432a769R76

**Comment by guedou** [comment]
That's the expected behavior, as there is no way to know which one is legitimate while detecting conflicts.
