### ISSUE TITLE
How to generate dynamic CSV files with realtime data?

### ISSUE THREAD

**Issue by karthikvee** [ANSSI-FR/tabi#5]
May I know how you are able to generate & use the dynamic CSV files with real time data instead of [static files](https://github.com/ANSSI-FR/tabi/tree/master/examples/annotation) as shown in[ repo](https://github.com/ANSSI-FR/tabi/tree/master/examples/annotation).

@nv-anssi @guedou @ol-anssi @pcapillon @gdedrouas

**Comment by ghost** [comment]
The CSV files were generated from the Internet Routing Registries (IRR) and RPKI providers such as RIPE. The example you refer to does not work with real time data.

However, if you want to build a live detection system, you could use the [RPKI validator API](https://www.ripe.net/support/documentation/developer-documentation/rpki-validator-api/rpki-validator-api) to export all Route Origin Authorisations and [NRTM](https://www.ripe.net/manage-ips-and-asns/db/nrtm-mirroring) to get real time route objects updates.
